DingTalk:
  ServerIp: 0.0.0.0
  ServerPort: 9001
  SendUrl : https://oapi.dingtalk.com/robot/send
  AccessToken : xxxxx
  Secret : xxxxx
DB:
  Mysql:
    default:
      DriverName: xxxxx
      Connection: xxxxx
      Port: xxxxx
      DbName: xxxxx
      UserName: xxxxx
      PassWord: xxxxx

