Server:
  Mode: release #debug test release
  Http:
    ServerIp : 0.0.0.0
    ServerPort: 9002
DingTalk:
  SendUrl : xxxxxxxxxxxxxxxxxxxx
  AccessToken : xxxxxxxxxxxxxxxxxxxx
  Secret : xxxxxxxxxxxxxxxxxxxx

#  SendUrl: https://oapi.dingtalk.com/robot/send
#  AccessToken: 7d6257c56c7007418d44988c17d0330c9d737348d2ba250b67b369a830a5e386
#  Secret: SECd14e9f040c603cf4e204342ef62d6b319515af4bc73a157577f8c94ad69d2efa


DB:
  Mysql:
    Default:
      DriverName: xxxxxxxxxxxxxxxxxxxx
      Connection: xxxxxxxxxxxxxxxxxxxx
      Port: xxxxxxxxxxxxxxxxxxxx
      DbName: xxxxxxxxxxxxxxxxxxxx
      UserName: xxxxxxxxxxxxxxxxxxxx
      PassWord: xxxxxxxxxxxxxxxxxxxx
    Andoncloud:
      DriverName: xxxxxxxxxxxxxxxxxxxx
      Connection: xxxxxxxxxxxxxxxxxxxx
      Port: xxxxxxxxxxxxxxxxxxxx
      DbName: xxxxxxxxxxxxxxxxxxxx
      UserName: xxxxxxxxxxxxxxxxxxxx
      PassWord: xxxxxxxxxxxxxxxxxxxx



